name: Build documentation

on:
  [push]
  #   branches:
  #     - main
  #     - doc
  #   paths:
  #     - "docs/**"
  # pull_request:
  #   branches:
  #     - main
  #     - doc

jobs:
  asciidocs:
    name: Build Asciidoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build PDF
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf -a allow-uri-read -D . README.adoc"  

      - id: bump
        uses: zwaldowski/match-label-action@v2
        with:
          allowed: patch
      - uses: zwaldowski/semver-release-action@v2
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}      

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF documentation
          path: README.pdf
